### ISSUE TITLE
Add counter name to exception message when negative value is detected

### ISSUE THREAD

**Issue by AntuanRokanten** [prometheus/client_java#1090]
### **Description**:

I am using `micrometer-registry-prometheus` version `1.13.0` with Spring Boot `3.3.0`, and sometimes I encounter the following exception when Prometheus scrapes metrics:

```
java.lang.IllegalArgumentException: -2.0: counters cannot have a negative value
at io.prometheus.metrics.model.snapshots.CounterSnapshot$CounterDataPointSnapshot.validate(CounterSnapshot.java:74)
at io.prometheus.metrics.model.snapshots.CounterSnapshot$CounterDataPointSnapshot.(CounterSnapshot.java:58)
at io.prometheus.metrics.model.snapshots.CounterSnapshot$CounterDataPointSnapshot.(CounterSnapshot.java:46)
at io.micrometer.prometheusmetrics.PrometheusMeterRegistry.lambda$newFunctionCounter$20(PrometheusMeterRegistry.java:372)
at io.micrometer.prometheusmetrics.MicrometerCollector.collect(MicrometerCollector.java:77)
at io.prometheus.metrics.model.registry.PrometheusRegistry.scrape(PrometheusRegistry.java:72)
at io.prometheus.metrics.model.registry.PrometheusRegistry.scrape(PrometheusRegistry.java:57)
at org.springframework.boot.actuate.metrics.export.prometheus.PrometheusScrapeEndpoint.scrape(PrometheusScrapeEndpoint.java:59)
```

The error message indicates that a counter has a negative value, but it does not specify which counter is causing the problem. This makes it difficult to identify the source of the issue in large applications with multiple counters.

### **Suggestion**:

It would be helpful if the exception message included the **name of the counter** that is causing the problem. This additional information would significantly improve the ability to troubleshoot issues, especially in complex applications.

**Comment by zeitlinger** [comment]
PR is welcome :smile:

**Comment by volkanto** [comment]
hey hi @zeitlinger, I see that there is already a pull request to solve this issue. But looks like it is kinda stale. Is there any progress on this? Thanks in advance.

**Comment by k-antonov** [comment]
Hi everyone! I think logging and skipping would be a broader behavioral change, because it would change the current fail-fast scrape model into partial success. I opened a smaller PR: it keeps the existing behaviour and adds a counter name to exception message. It seemed to me that Micrometer is the best place for this, since it has access to meter name during creating problematic snapshot: https://github.com/micrometer-metrics/micrometer/pull/7327
