### ISSUE TITLE
`IllegalAccessError` thrown when calling `name` method of Counter and Gauge metric

### ISSUE THREAD

**Issue by jgagnon44** [prometheus/client_java#1172]
I just updated from version 1.3.1 to 1.3.2 for the Prometheus Java API and immediately ran into some unusual exceptions that are triggered when the `name` method is invoked for the builder of the Counter metric class.

Here is pertinent information WRT my set-up:

$ java -version
java version "17.0.12" 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.12+8-LTS-286, mixed mode, sharing)

Spring Boot 3.3.4

pom.xml:

```
  <properties>
    <prometheus-metrics.version>1.3.2</prometheus-metrics.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
          <groupId>io.prometheus</groupId>
          <artifactId>prometheus-metrics-core</artifactId>
          <version>${prometheus-metrics.version}</version>
      </dependency>

      <dependency>
          <groupId>io.prometheus</groupId>
          <artifactId>prometheus-metrics-exporter-httpserver</artifactId>
          <version>${prometheus-metrics.version}</version>
      </dependency>
    </dependencies>
 </dependencyManagement>
```
 
Sample code that triggers the exception:

```
  private Counter createCounter(String name, List<String> labels) {
    Counter.Builder builder = Counter.builder();
    builder.name(name);

    if (labels != null && !labels.isEmpty()) {
      builder.labelNames(labels.stream().toArray(String[]::new));
    }

    return builder.build();
  }
```

Example stack trace:

```
java.lang.IllegalAccessError: class io.prometheus.metrics.core.metrics.MetricWithFixedMetadata$Builder tried to access method 'java.lang.String io.prometheus.metrics.model.snapshots.PrometheusNaming.validateMetricName(java.lang.String)' (io.prometheus.metrics.core.metrics.MetricWithFixedMetadata$Builder and io.prometheus.metrics.model.snapshots.PrometheusNaming are in unnamed module of loader 'app')
	at io.prometheus.metrics.core.metrics.MetricWithFixedMetadata$Builder.name(MetricWithFixedMetadata.java:60)
	at io.prometheus.metrics.core.metrics.Counter$Builder.name(Counter.java:240)
	at com.beastcode.devops.metricsbroker.provider.TestMetricsRegistry.createCounter(TestMetricsRegistry.java:618)
	at com.beastcode.devops.metricsbroker.provider.TestMetricsRegistry.setUpCounterAndDataPoint(TestMetricsRegistry.java:633)
	at com.beastcode.devops.metricsbroker.provider.TestMetricsRegistry.GIVEN_nullName_WHEN_registerDataPoint_THEN_dataPointNotRegistered(TestMetricsRegistry.java:329)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by fstab** [comment]
Hi, thanks for the bug report.

The `client_java` library includes a couple of examples, and the example here works:

https://github.com/prometheus/client_java/blob/397738e33bf00f0219bbed92f7a8a5e78b949cb0/examples/example-exporter-httpserver/src/main/java/io/prometheus/metrics/examples/httpserver/Main.java#L22-L27

Do you see the difference why this is working and your example isn't?

Are you using Java modules?

**Comment by jgagnon44** [comment]
Not sure what Java modules are, so I'm guessing the answer is: probably not. What relevance might that have to this issue?

**Comment by jgagnon44** [comment]
I reviewed the code and found two cases:

```
  private Counter createCounter(String name) {
    Counter.Builder builder = Counter.builder();
    builder.name(name);
    return builder.build();
  }

  private Counter createCounter(String name, List<String> labels) {
    Counter.Builder builder = Counter.builder();
    builder.name(name);

    if (labels != null && !labels.isEmpty()) {
      builder.labelNames(labels.stream().toArray(String[]::new));
    }

    return builder.build();
  }
```

Are there other calls to the `builder` that are required before calling `build()` that I may have missed?

**Comment by fstab** [comment]
I created a simple example project with your code here: https://github.com/fstab/counter-builder-example

It works, when I point my browser to [http://localhost:9400/metrics](http://localhost:9400/metrics) I see the metrics as expected:

```
# TYPE counter1_total counter
counter1_total 1.0
# TYPE counter2_total counter
counter2_total{label1="a",label2="b"} 1.0
```

Can you see the difference between the example project and your project?

**Comment by fstab** [comment]
No, you don't need modules. I was just guessing that some issue with modules might be causing this. However, if you don't use them it has to be something else.

I'm happy to help, but I need to be able to reproduce the issue, otherwise there's not much I can do.

**Comment by fstab** [comment]
> I am using Spring Boot

Oh, now I have an idea: Spring boot also includes the Prometheus `client_java` library. Maybe you ended up with multiple different versions, one that comes with Spring and another one that you included in your pom directly?

Try printing the Maven dependency tree and exclude potential duplicate dependencies.

**Comment by jgagnon44** [comment]
Having a separate issue printing the dependency tree. I am curious how to determine how/where Spring Boot is pulling in the io.prometheus code and how I can exclude it.

**Comment by jgagnon44** [comment]
I am seeing this is my Maven dependencies (this is from eclipse):
![image](https://github.com/user-attachments/assets/d463c62c-0481-4dd5-87f1-37480c95969a)

**Comment by fstab** [comment]
Try to run this on the command line:

```
mvn dependency:tree
```

**Comment by jgagnon44** [comment]
Yeah, I tried that an ran into a cert issue that's preventing me from accessing some dependencies. I need to figure out how to fix that before I can do this.

**Comment by jgagnon44** [comment]
Fixed that issue.
Here's the results of running `mvn dependency:tree`:

```
[INFO] com.beastcode.devops:metric-broker:jar:3.1.0
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:3.3.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:3.3.4:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:3.3.4:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-autoconfigure:jar:3.3.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:3.3.4:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.17.2:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.17.2:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.17.2:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:3.3.4:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:10.1.30:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:10.1.30:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:10.1.30:compile
[INFO] |  +- org.springframework:spring-web:jar:6.1.13:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:6.1.13:compile
[INFO] |  |  \- io.micrometer:micrometer-observation:jar:1.13.4:compile
[INFO] |  |     \- io.micrometer:micrometer-commons:jar:1.13.4:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:6.1.13:compile
[INFO] |     +- org.springframework:spring-aop:jar:6.1.13:compile
[INFO] |     +- org.springframework:spring-context:jar:6.1.13:compile
[INFO] |     \- org.springframework:spring-expression:jar:6.1.13:compile
[INFO] +- org.springframework.boot:spring-boot-starter-log4j2:jar:3.3.4:compile
[INFO] |  +- org.apache.logging.log4j:log4j-slf4j2-impl:jar:2.23.1:compile
[INFO] |  |  \- org.apache.logging.log4j:log4j-api:jar:2.23.1:compile
[INFO] |  +- org.apache.logging.log4j:log4j-core:jar:2.23.1:compile
[INFO] |  \- org.apache.logging.log4j:log4j-jul:jar:2.23.1:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:3.3.4:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:3.3.4:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:3.3.4:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.9.0:test
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:4.0.2:test
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:2.1.3:test
[INFO] |  +- net.minidev:json-smart:jar:2.5.1:test
[INFO] |  |  \- net.minidev:accessors-smart:jar:2.5.1:test
[INFO] |  |     \- org.ow2.asm:asm:jar:9.6:test
[INFO] |  +- org.assertj:assertj-core:jar:3.25.3:test
[INFO] |  |  \- net.bytebuddy:byte-buddy:jar:1.14.19:test
[INFO] |  +- org.awaitility:awaitility:jar:4.2.2:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.10.3:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.10.3:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.10.3:test
[INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.10.3:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.10.3:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.10.3:test
[INFO] |  +- org.mockito:mockito-core:jar:5.11.0:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.14.19:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.3:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:5.11.0:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.3:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-core:jar:6.1.13:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:6.1.13:compile
[INFO] |  +- org.springframework:spring-test:jar:6.1.13:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.9.1:test
[INFO] +- jakarta.annotation:jakarta.annotation-api:jar:3.0.0:compile
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.17.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.17.2:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.17.2:compile
[INFO] |  +- org.yaml:snakeyaml:jar:2.2:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.17.2:compile
[INFO] +- com.networknt:json-schema-validator:jar:1.5.2:compile
[INFO] |  +- com.ethlo.time:itu:jar:1.10.2:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:2.0.16:compile
[INFO] +- io.prometheus:prometheus-metrics-core:jar:1.3.1:compile
[INFO] |  +- io.prometheus:prometheus-metrics-model:jar:1.2.1:compile
[INFO] |  +- io.prometheus:prometheus-metrics-config:jar:1.2.1:compile
[INFO] |  \- io.prometheus:prometheus-metrics-tracer-initializer:jar:1.2.1:compile
[INFO] |     +- io.prometheus:prometheus-metrics-tracer-common:jar:1.2.1:compile
[INFO] |     +- io.prometheus:prometheus-metrics-tracer-otel:jar:1.2.1:compile
[INFO] |     \- io.prometheus:prometheus-metrics-tracer-otel-agent:jar:1.2.1:compile
[INFO] +- io.prometheus:prometheus-metrics-exporter-httpserver:jar:1.3.1:compile
[INFO] |  \- io.prometheus:prometheus-metrics-exporter-common:jar:1.2.1:compile
[INFO] |     \- io.prometheus:prometheus-metrics-exposition-formats:jar:1.2.1:compile
[INFO] |        \- io.prometheus:prometheus-metrics-shaded-protobuf:jar:1.2.1:compile
[INFO] \- com.beastcode.devops:metric-broker-common:jar:2.0.0:compile
```

**Comment by jgagnon44** [comment]
Here's the tree after switching to 1.3.2:

```
[INFO] com.beastcode.devops:metric-broker:jar:3.1.0
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:3.3.5:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:3.3.5:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:3.3.5:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-autoconfigure:jar:3.3.5:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:3.3.5:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.17.2:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.17.2:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.17.2:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:3.3.5:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:10.1.31:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:10.1.31:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:10.1.31:compile
[INFO] |  +- org.springframework:spring-web:jar:6.1.14:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:6.1.14:compile
[INFO] |  |  \- io.micrometer:micrometer-observation:jar:1.13.6:compile
[INFO] |  |     \- io.micrometer:micrometer-commons:jar:1.13.6:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:6.1.14:compile
[INFO] |     +- org.springframework:spring-aop:jar:6.1.14:compile
[INFO] |     +- org.springframework:spring-context:jar:6.1.14:compile
[INFO] |     \- org.springframework:spring-expression:jar:6.1.14:compile
[INFO] +- org.springframework.boot:spring-boot-starter-log4j2:jar:3.3.5:compile
[INFO] |  +- org.apache.logging.log4j:log4j-slf4j2-impl:jar:2.23.1:compile
[INFO] |  |  \- org.apache.logging.log4j:log4j-api:jar:2.23.1:compile
[INFO] |  +- org.apache.logging.log4j:log4j-core:jar:2.23.1:compile
[INFO] |  \- org.apache.logging.log4j:log4j-jul:jar:2.23.1:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:3.3.5:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:3.3.5:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:3.3.5:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.9.0:test
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:4.0.2:test
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:2.1.3:test
[INFO] |  +- net.minidev:json-smart:jar:2.5.1:test
[INFO] |  |  \- net.minidev:accessors-smart:jar:2.5.1:test
[INFO] |  |     \- org.ow2.asm:asm:jar:9.6:test
[INFO] |  +- org.assertj:assertj-core:jar:3.25.3:test
[INFO] |  |  \- net.bytebuddy:byte-buddy:jar:1.14.19:test
[INFO] |  +- org.awaitility:awaitility:jar:4.2.2:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.10.5:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.10.5:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.10.5:test
[INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.10.5:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.10.5:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.10.5:test
[INFO] |  +- org.mockito:mockito-core:jar:5.11.0:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.14.19:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.3:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:5.11.0:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.3:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-core:jar:6.1.14:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:6.1.14:compile
[INFO] |  +- org.springframework:spring-test:jar:6.1.14:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.9.1:test
[INFO] +- jakarta.annotation:jakarta.annotation-api:jar:3.0.0:compile
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.17.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.17.2:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.17.2:compile
[INFO] |  +- org.yaml:snakeyaml:jar:2.2:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.17.2:compile
[INFO] +- com.networknt:json-schema-validator:jar:1.5.2:compile
[INFO] |  +- com.ethlo.time:itu:jar:1.10.2:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:2.0.16:compile
[INFO] +- io.prometheus:prometheus-metrics-core:jar:1.3.2:compile
[INFO] |  +- io.prometheus:prometheus-metrics-model:jar:1.2.1:compile
[INFO] |  +- io.prometheus:prometheus-metrics-config:jar:1.2.1:compile
[INFO] |  \- io.prometheus:prometheus-metrics-tracer-initializer:jar:1.2.1:compile
[INFO] |     +- io.prometheus:prometheus-metrics-tracer-common:jar:1.2.1:compile
[INFO] |     +- io.prometheus:prometheus-metrics-tracer-otel:jar:1.2.1:compile
[INFO] |     \- io.prometheus:prometheus-metrics-tracer-otel-agent:jar:1.2.1:compile
[INFO] +- io.prometheus:prometheus-metrics-exporter-httpserver:jar:1.3.2:compile
[INFO] |  \- io.prometheus:prometheus-metrics-exporter-common:jar:1.2.1:compile
[INFO] |     \- io.prometheus:prometheus-metrics-exposition-formats:jar:1.2.1:compile
[INFO] |        \- io.prometheus:prometheus-metrics-shaded-protobuf:jar:1.2.1:compile
[INFO] \- com.beastcode.devops:metric-broker-common:jar:2.0.0:compile
```

**Comment by jgagnon44** [comment]
@fstab Please let me know if the information I've provided above is helpful.

**Comment by jgagnon44** [comment]
Just by chance, I discovered that I get the same exception thrown when calling the `name `method for a Gauge metric as well.

**Comment by fstab** [comment]
Thanks @jgagnon44! `prometheus-metrics-core` 1.3.2 depending on `prometheus-metrics-model` 1.2.1 doesn't look right. Could you try to add all `prometheus-metrics-*` dependencies explicitly to your `pom.xml` with version 1.3.2?

* `prometheus-metrics-model`
* `prometheus-metrics-config`
* `prometheus-metrics-tracer-initializer`
* `prometheus-metrics-tracer-common`
* `prometheus-metrics-tracer-otel`
* `prometheus-metrics-tracer-otel-agent`
* `prometheus-metrics-exporter-httpserver`
* `prometheus-metrics-exporter-common`
* `prometheus-metrics-exposition-formats`
* `prometheus-metrics-shaded-protobuf`

I suspect that you get `prometheus-metrics-core` 1.3.2 because you explicitly have it in your `pom.xml`, and get the other dependencies as version `1.2.1` because that's defined in Spring's parent pom. So you end up with a mix of versions.

**Comment by zeitlinger** [comment]
Here's how you should do it - will to add this to the docs later, too:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>prom-demo</artifactId>
    <version>1.0-SNAPSHOT</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.4</version>
    </parent>

    <properties>
        <maven.compiler.source>19</maven.compiler.source>
        <maven.compiler.target>19</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.prometheus</groupId>
                <artifactId>prometheus-metrics-bom</artifactId>
                <version>1.3.2</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>prometheus-metrics-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>prometheus-metrics-instrumentation-jvm</artifactId>
        </dependency>
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>prometheus-metrics-exporter-httpserver</artifactId>
        </dependency>
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>prometheus-metrics-exporter-opentelemetry</artifactId>
        </dependency>
    </dependencies>
</project>

```

**Comment by jgagnon44** [comment]
Following something similar to what was provided in the example POM above, I was able to get this to work now with version 1.3.2. Thanks for the help.

**Comment by zeitlinger** [comment]
I've also added the description to the GitHub pages now (quick start)
