### ISSUE TITLE
Be compatible with IBM JDK in a lenient way

### ISSUE THREAD

**Issue by davidkarlsen** [prometheus/client_java#174]
DefaultExports.initialize() will add register (among other) StandardExports.
StandardExports has two com.sun.management classes.
It will fail on a IBM JDK with:
```
[1/10/17 10:19:50:691 CET] 00000021 com.ibm.ws.webcontainer.webapp                               E SRVE0283E: Exception caught while initializing context: java.lang.ClassCastException: com.ibm.lang.management.UnixExtendedOperatingSystem incompatible with com.sun.management.OperatingSystemMXBean
        at io.prometheus.client.hotspot.StandardExports.<init>(StandardExports.java:43)
        at io.prometheus.client.hotspot.DefaultExports.initialize(DefaultExports.java:23)
```

I think it would be better to 
1) use java.lang.managment where possible, and where it does not provide the additional metrics we want:
2) use some classload-test to see if the classes are available, and if not, skip registering.

**Comment by brian-brazil** [comment]
Default exports is in the Hotspot module, and thus doesn't support non-Hotspot JVMs such as IBM's.

> use java.lang.managment where possible, and where it does not provide the additional metrics we want:

We do this a but, however this isn't part of the Java spec and thus varies across JVM implementations. Basically we're hardcoding to what Hotspot provides.

> use some classload-test to see if the classes are available, and if not, skip registering.

I was informed this wouldn't work, but if you can get it working that'd be great.
