### ISSUE TITLE
npe in $MetricFamilySamplesEnumeration.includedCollectorIterator since 0.0.23

### ISSUE THREAD

**Issue by jorgheymans** [prometheus/client_java#264]
Hi,

I just upgraded my spring-boot (1.5.4) application to 0.0.23 and getting this in the logs each time prometheus scrapes the metrics. Reverting back to 0.0.22 fixed the issue

```
java.lang.NullPointerException: null
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.includedCollectorIterator(CollectorRegistry.java:148) ~[simpleclient-0.0.23.jar:na]
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.<init>(CollectorRegistry.java:143) ~[simpleclient-0.0.23.jar:na]
	at io.prometheus.client.CollectorRegistry.filteredMetricFamilySamples(CollectorRegistry.java:131) ~[simpleclient-0.0.23.jar:na]
	at io.prometheus.client.spring.boot.PrometheusEndpoint.writeRegistry(PrometheusEndpoint.java:32) ~[simpleclient_spring_boot-0.0.23.jar:na]
	at io.prometheus.client.spring.boot.PrometheusMvcEndpoint.value(PrometheusMvcEndpoint.java:38) ~[simpleclient_spring_boot-0.0.23.jar:na]
```

**Comment by brian-brazil** [comment]
Fixed by #256 I believe.

**Comment by Tigraine** [comment]
I just rolled back to 0.22 and it worked

**Comment by sanjaychandak** [comment]
I am using 0.0.23 with Spring Boot 1.5.4.RELEASE but still I get the java.lang.NullPointerException: null
at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.includedCollectorIterator(CollectorRegistry.java:148)

Which version has this issue been fixed?

**Comment by Tigraine** [comment]
I believe the fix will go into the next version. I downgraded to 0.22 and it works there
