### ISSUE TITLE
Compatibility with Spring Boot 2.0.0.M4

### ISSUE THREAD

**Issue by sbueringer** [prometheus/client_java#295]
Hi,

I just switched to the new Spring Boot version 2.0.0.M4 and there seems to be a compatibility issue:

Dependencies:
````
compile "org.springframework.boot:spring-boot-starter-actuator:2.0.0.M4"
compile 'io.prometheus:simpleclient_spring_boot:0.0.26'
compile 'io.prometheus:simpleclient_servlet:0.0.26'
compile 'io.prometheus:simpleclient_hotspot:0.0.26'
````
 
Stacktrace:
````
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [***.Application]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class io.prometheus.client.spring.boot.PrometheusEndpointConfiguration
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:620) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:300) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:198) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:166) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:316) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:271) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:94) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:693) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:122) ~[spring-boot-2.0.0.M4.jar:2.0.0.M4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.0.0.M4.jar:2.0.0.M4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:386) [spring-boot-2.0.0.M4.jar:2.0.0.M4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.M4.jar:2.0.0.M4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1245) [spring-boot-2.0.0.M4.jar:2.0.0.M4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1233) [spring-boot-2.0.0.M4.jar:2.0.0.M4]
	at ***.ApplicationKt.main(Application.kt:49) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-2.0.0.M4.jar:2.0.0.M4]
Caused by: java.lang.IllegalStateException: Failed to introspect annotated methods on class io.prometheus.client.spring.boot.PrometheusEndpointConfiguration
	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:169) ~[spring-core-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.context.annotation.ConfigurationClassParser.retrieveBeanMethodMetadata(ConfigurationClassParser.java:390) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:315) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:610) ~[spring-context-5.0.0.RC4.jar:5.0.0.RC4]
	... 22 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/actuate/endpoint/AbstractEndpoint
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_60]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_60]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_60]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_60]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_60]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_60]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_60]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_60]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_60]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_60]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_60]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_60]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_60]
	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:158) ~[spring-core-5.0.0.RC4.jar:5.0.0.RC4]
	... 26 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.endpoint.AbstractEndpoint
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_60]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_60]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_60]
	... 42 common frames omitted
````

**Comment by checketts** [comment]
Note the `java.lang.ClassNotFoundException: org.springframework.boot.actuate.endpoint.AbstractEndpoint`  That class moved in SpringBoot 2. 

Since SpringBoot 2 has direct support for Prometheus now (via Micrometer.io) that module should be deprecated.

**Comment by sbueringer** [comment]
Oh thanks very much for the information. I wasn't aware of that.
