### ISSUE TITLE
NoSuchMethodError error on CollectorRegistry.filteredMetricFamilySamples when collecting DefaultExports

### ISSUE THREAD

**Issue by iros** [prometheus/client_java#316]
I am attempting to collect default exports in addition to a few metrics, but adding DefaultExports.initialize() results in the error below.
Removing that line will produce the metrics I am collecting (see as an example a basic counter.)

Stacktrace:

```
java.lang.NoSuchMethodError: io.prometheus.client.CollectorRegistry.filteredMetricFamilySamples(Ljava/util/Set;)Ljava/util/Enumeration;
	at io.prometheus.client.exporter.MetricsServlet.doGet(MetricsServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:681)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:449)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1084)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:376)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1018)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:451)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
	at java.lang.Thread.run(Thread.java:748)
```

Here is sample code to replicate:

```java
import java.net.InetSocketAddress;

import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.jetty.servlet.ServletContextHandler;
import org.eclipse.jetty.servlet.ServletHolder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.prometheus.client.exporter.MetricsServlet;
import io.prometheus.client.hotspot.DefaultExports;
import mlab.dataviz.metrics.HTTPRootHandler;
import io.prometheus.client.Counter;

public class Metrics implements Runnable {
	private static final Logger LOG = LoggerFactory.getLogger(Runner.class);

	private InetSocketAddress port;
	private Counter requestsCounter;

	public Metrics() {
		// start prometheus collection server on port 9090
		this.port = new InetSocketAddress(9090);

		// track number of server boots, so we have a sense of how much these are
		// failing.
		this.bootCounter = Counter.build().name("simple_counter")
				.help("Simple Counter")
				.register();

		this.bootCounter.inc();
	}

	@Override
	public void run() {

		Server server = new Server(this.port);

		ServerConnector connector = new ServerConnector(server);

		connector.setPort(9090);
		connector.setHost("localhost");

		ServletContextHandler context = new ServletContextHandler();
		context.setContextPath("/");
		server.setHandler(context);

		// Add root servlet (outputs hello world.)
		context.addServlet(new ServletHolder(new HTTPRootHandler()), "/");
		
		// Add metrics servlet
		context.addServlet(new ServletHolder(new MetricsServlet()), "/metrics");

		// Add metrics about CPU, JVM memory etc.
		DefaultExports.initialize();

		try {
			// Start the webserver.
			server.start();
			server.join();
		} catch (Exception e) {
			e.printStackTrace();
			LOG.error(e.getLocalizedMessage());
		}
	}
}
```

In another class:
```java
       public static void main(String[] args) throws InterruptedException {
		// Prometheus http server
		Metrics m = new Metrics();
		Thread metricsThread = new Thread(m);
		metricsThread.start();
      }
```

**Comment by brian-brazil** [comment]
What JVM are you using?

**Comment by iros** [comment]
JavaSE-1.8 (Java SE 8 [1.8.0_144])

**Comment by brian-brazil** [comment]
And which versions are you using of each artifact?

**Comment by iros** [comment]
Here are the relevant pom dependencies:

```xml
<!-- prometheus - core -->
		<dependency>
			<groupId>io.prometheus</groupId>
			<artifactId>simpleclient</artifactId>
			<version>0.0.10</version>
		</dependency>

		<!-- prometheus - Exposition HTTPServer -->
		<dependency>
			<groupId>io.prometheus</groupId>
			<artifactId>simpleclient_httpserver</artifactId>
			<version>0.1.0</version>
		</dependency>

		<!-- Hotspot JVM metrics -->
		<dependency>
			<groupId>io.prometheus</groupId>
			<artifactId>simpleclient_hotspot</artifactId>
			<version>0.1.0</version>
		</dependency>

		<dependency>
			<groupId>io.prometheus</groupId>
			<artifactId>simpleclient_servlet</artifactId>
			<version>0.1.0</version>
		</dependency>

		<!-- prometheus - Pushgateway exposition -->
		<dependency>
			<groupId>io.prometheus</groupId>
			<artifactId>simpleclient_pushgateway</artifactId>
			<version>0.1.0</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-project -->
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-server</artifactId>
			<version>9.0.2.v20130417</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-servlet</artifactId>
			<version>9.0.2.v20130417</version>
		</dependency>
```

**Comment by brian-brazil** [comment]
You should always use consistent versions of the various parts of the simpleclient, 0.0.10 is quite old compared to the rest.

In addition, the node exporter should already expose all you need to track reboots.

**Comment by iros** [comment]
Ah you are correct. Thank you so much for catching that. Hopefully this will be useful to someone else. Closing. 👍
