### ISSUE TITLE
simpleclient_spring_boot not working with Spring Boot 2.0.0

### ISSUE THREAD

**Issue by r0kas** [prometheus/client_java#372]
Hi,

I have Spring Boot 2.0.0 application and would like to get it's metrics through /prometheus endpoint.
Unfortunately after adding @EnablePrometheusEndpoint and @EnableSpringBootMetricsCollector annotations to my apps configuration it fails to build due to missing class dependency.
```
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.endpoint.AbstractEndpoint
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_151]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_151]
	... 49 common frames omitted
```

This class is imported by PrometheusEndpoint.class in io.prometheus.client.spring.boot package of simpleclient_spring_boot-0.3.0.
simpleclient_spring_boot-0.3.0 has a dependency of Spring Boot Actuator 1.5.4 and it fails to find `org.springframework.boot.actuate.endpoint.AbstractEndpoint` class in Spring Boot Actuator 2.0.0 as it's not present anymore.

I can see that you still use Spring Boot 1.5.4 dependencies in your 0.3.1-SNAPSHOT version.
Do you have plans to support Spring Boot 2.0.0 in short future?

**Comment by brian-brazil** [comment]
This library only supports 1, and there's no plans to support 2 directly. You can continue to use normal direct instrumentation with any JVM-based application.
