### ISSUE TITLE
The class `sun.misc.Unsafe` is not avilable in JDK 11

### ISSUE THREAD

**Issue by apmasell** [prometheus/client_java#468]
The `Striped64` class depends on `sun.misc.Unsafe` which has been removed in JDK 11, resulting in a class not found error on loading when using Jigsaw modules.

```
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/Unsafe
	at simpleclient@0.6.0/io.prometheus.client.Striped64.getUnsafe(Striped64.java:316)
	at simpleclient@0.6.0/io.prometheus.client.Striped64.<clinit>(Striped64.java:296)
	at simpleclient@0.6.0/io.prometheus.client.Gauge$Child.<init>(Gauge.java:137)
	at simpleclient@0.6.0/io.prometheus.client.Gauge.newChild(Gauge.java:98)
	at simpleclient@0.6.0/io.prometheus.client.Gauge.newChild(Gauge.java:66)
	at simpleclient@0.6.0/io.prometheus.client.SimpleCollector.labels(SimpleCollector.java:76)
	at simpleclient@0.6.0/io.prometheus.client.SimpleCollector.initializeNoLabelsChild(SimpleCollector.java:107)
	at simpleclient@0.6.0/io.prometheus.client.SimpleCollector.<init>(SimpleCollector.java:174)
	at simpleclient@0.6.0/io.prometheus.client.Gauge.<init>(Gauge.java:69)
	at simpleclient@0.6.0/io.prometheus.client.Gauge$Builder.create(Gauge.java:75)
	at simpleclient@0.6.0/io.prometheus.client.Gauge$Builder.create(Gauge.java:72)
	at simpleclient@0.6.0/io.prometheus.client.SimpleCollector$Builder.register(SimpleCollector.java:245)
	at simpleclient@0.6.0/io.prometheus.client.SimpleCollector$Builder.register(SimpleCollector.java:238)
	at ca.on.oicr.gsi.runscanner.server/ca.on.oicr.gsi.runscanner.server.util.Scheduler.<clinit>(Scheduler.java:160)
	at ca.on.oicr.gsi.runscanner.server/ca.on.oicr.gsi.runscanner.server.Server.main(Server.java:26)
Caused by: java.lang.ClassNotFoundException: sun.misc.Unsafe
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 15 more
```

This isn't a priority for me, but wanted you to know.

**Comment by brian-brazil** [comment]
What's the alternative? And that still works back to Java 6?

**Comment by apmasell** [comment]
Different options depending on what is going on. It looks like `DoubleAdder` is the real class here that's a backport of the `java.util.atomic.DoubleAdder`. I think this could be solved in one of two ways using a [multi-release JAR](https://openjdk.java.net/jeps/238). This will raise the build version of the library to Java 9, but the release version can remain at 1.6.

Option 1:
Write two versions of `DoubleAdder`; one as it is now and one that is a wrapper around `java.util.atomic.DoubleAdder`. Create a multi-release JAR that uses the wrapper version for Java 9 and leave `Striped64` dead on the class path; it should be fine to leave there as long as nothing attempts to load it.

Option 2:
Refactor `Striped64` to push all the unsafe operations into a helper class. Write 2 versions of the helper class; one that uses the `Unsafe` operations and one which uses `VarHandle` to do the atomic operations. Create a multi-release JAR that uses the `VarHandle` version for Java 9.

I think option 2 is safer in terms of leaving unloadable classes on the classpath. Given you are maintaining your own copy of a J2SE class, I think option 1 is closer to the end state you want to be in when support for 1.6 and 1.7 is being sunset.

The risks in option 1 can be mitigated by adding automatic module support to the manifest and restricting access to things like Spring that like to load all classes it can find.

**Comment by brian-brazil** [comment]
How about option 1, and also putting in a dummy Striped64 class?

**Comment by apmasell** [comment]
Maybe. It would have to also create dummy classes for the inner classes of `Striped64`. That's easy for `Cell`, but there's an AIC: https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/Striped64.java#L320
I would recommend refactoring this into a named class. The erasure means that the dummy version of this class can take a different type argument since that one won't be visible.

**Comment by apmasell** [comment]
Revisiting this issue, I want to present option 3: https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/atomic/AtomicLongFieldUpdater.html
It does what you're doing now with less code and is available from Java 1.5 to the present day. If that sounds good, I can make a PR.

**Comment by brian-brazil** [comment]
Is that going to be as performant though?

**Comment by apmasell** [comment]
Yes. It uses the same underlying implementation.

**Comment by brian-brazil** [comment]
AtomicLong seems to be doing something much simpler than DoubleAdder. Are you sure AtomicLong is aiming to do per-core values to avoid contention?

**Comment by apmasell** [comment]
`AtomicLong` is not the same as `AtomicLongFieldUpdater`. I'm only replacing the calls to `sun.misc.Unsafe`, which is what `AtomicLongFieldUpdater` is doing in its implementation.

**Comment by brian-brazil** [comment]
That sounds workable.
