### ISSUE TITLE
Response Status Code does not match

### ISSUE THREAD

**Issue by nielsmite** [prometheus/client_java#509]
Following your example in the README.md, the following code 
```
 @Test
    public void someGauge() throws IOException {
        CollectorRegistry registry = new CollectorRegistry();
        Gauge duration = Gauge.build()
                              .name("my_batch_job_duration_seconds").help("Duration of my job in seconds.")
                              .register(registry);

        PushGateway pg = new PushGateway("127.0.0.1:9091");

        pg.pushAdd(registry, "my_batch_job");
    }
```
is throwing
```
java.io.IOException: Response code from http://127.0.0.1:9091/metrics/job/my_batch_job was 200
	at io.prometheus.client.exporter.PushGateway.doRequest(PushGateway.java:325)
	at io.prometheus.client.exporter.PushGateway.pushAdd(PushGateway.java:160)

```

Used versions are:
```
 pushgateway --version
pushgateway, version 1.0.0 (branch: HEAD, revision: cc61f46971f5eb7a5be64e80c2ee03857ddbb41a)
  build user:       root@58be538fc30e
  build date:       20191015-19:58:18
  go version:       go1.13.1
```

and
```
compile 'io.prometheus:simpleclient:0.7.0'
compile 'io.prometheus:simpleclient_pushgateway:0.7.0'
```

Seems like with version 1.0.0 the expected status code has changed?

**Comment by ConorPFarrell** [comment]
We have also run across this issue, it would be great to get an idea of when a new version of the client will be released - I can see that the expected response code has already changed in master.

**Comment by brian-brazil** [comment]
I was going to do it last week, but life got in the way. Should be this week.

**Comment by nielsmite** [comment]
Thanks so much!
