### ISSUE TITLE
Build failed under Spring boot 2.5.6

### ISSUE THREAD

**Issue by renekt** [prometheus/client_java#713]
Hi, spring-boot-client build failed under **Spring boot 2.5.6** enviroment.

**Error msg:**
```bash
20:33:26.298 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [cn.slb.brokerprometheus.BrokerPrometheusApplication]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class io.prometheus.client.spring.boot.PrometheusEndpointConfiguration
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:610) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:311) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:207) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:175) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.6.jar:2.5.6]
```

**Cause:**
  the version of spring-boot in **client_java/simpleclient_spring_boot/**  is 1.5.4.RELEASE, but current GA version of spring-boot is 2.5.6, the package path of **ConditionalOnEnabledEndpoint**  has been moved from _package org.springframework.boot.actuate.condition_ to _package org.springframework.boot.actuate.autoconfigure.endpoint.condition_

**Suggestion:** update the spring-boot dependencies version to recent GA version: 2.5.6.

Thank you.

**Comment by Zeouterlimits** [comment]
While it's not as clear as it should be, you should not use simpleclient_spring_boot with Spring Boot 2, it does not support it.
Instead use Spring Boot's actuator & micrometer support, with the plain java io.prometheus simpleclient.
See this answer: https://github.com/prometheus/client_java/issues/299#issuecomment-358064836

**Comment by fstab** [comment]
Agree with @Zeouterlimits. As Spring Boot 2 ships with [Micrometer's Prometheus Registry](https://micrometer.io/docs/registry/prometheus) I don't see the need for implementing Spring Boot 2 support in `client_java`.
