### ISSUE TITLE
compiling java client servlet doesn't pass tests

### ISSUE THREAD

**Issue by cfedersp** [prometheus/client_java#79]
I'm running java 7.045 and compiling 0.0.11-SNAPSHOT.
Also, If I skipTests, I deploy to jboss 7.1.1, but get no content back from the metrics servlet.

maven test output:
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.prometheus.client.exporter.PushGatewayTest
Tests run: 22, Failures: 0, Errors: 15, Skipped: 0, Time elapsed: 2.178 sec <<< FAILURE! - in io.prometheus.client.exporter.PushGatewayTest
testPush(io.prometheus.client.exporter.PushGatewayTest)  Time elapsed: 0.058 sec  <<< ERROR!
java.net.SocketException: Invalid argument
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:687)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:658)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1323)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at io.prometheus.client.exporter.PushGateway.doRequest(PushGateway.java:271)
	at io.prometheus.client.exporter.PushGateway.push(PushGateway.java:73)
	at io.prometheus.client.exporter.PushGatewayTest.testPush(PushGatewayTest.java:46)

testOldPushCollector(io.prometheus.client.exporter.PushGatewayTest)  Time elapsed: 0.059 sec  <<< ERROR!
java.net.SocketException: Invalid argument
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:687)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:658)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1323)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at io.prometheus.client.exporter.PushGateway.doRequest(PushGateway.java:271)
	at io.prometheus.client.exporter.PushGateway.push(PushGateway.java:190)
	at io.prometheus.client.exporter.PushGateway.push(PushGateway.java:204)
	at io.prometheus.client.exporter.PushGatewayTest.testOldPushCollector(PushGatewayTest.java:220)

**Comment by brian-brazil** [comment]
I hit the exact same last week, this is a bug in Java on OS X; see https://bugs.openjdk.java.net/browse/JDK-8021820

Upgrade to a newer JVM to fix this.

**Comment by cfedersp** [comment]
thank you, compile and tests passed with jdk1.7.0_79!
