### ISSUE TITLE
client-java nullpointer exception

### ISSUE THREAD

**Issue by wangjingbomail** [prometheus/client_java#84]
jdk 1.8.0_45-b14
when running lient_java/examples/jvmstat    Main.java

Exception in thread "main" java.lang.NullPointerException
	at org.reflections.Reflections.scan(Reflections.java:220)
	at org.reflections.Reflections.scan(Reflections.java:166)
	at org.reflections.Reflections.<init>(Reflections.java:94)
	at io.prometheus.client.Prometheus.collectAnnotatedFields(Prometheus.java:190)
	at io.prometheus.client.Prometheus.initialize(Prometheus.java:201)
	at io.prometheus.client.Prometheus.defaultInitialize(Prometheus.java:274)
	at io.prometheus.client.examples.guice.Server.configure(Server.java:47)
	at io.prometheus.client.examples.guice.Main.run(Main.java:61)
	at io.prometheus.client.examples.jvmstat.Main.main(Main.java:45)

This also happens when I use  Prometheus.defaultInitialize();
<dependency>
    <groupId>io.prometheus.client.utility</groupId>
    <artifactId>servlet</artifactId>
    <version>0.0.10</version>
</dependency>

**Comment by brian-brazil** [comment]
The original client is going to be deprecated in the very near future, you should use the simpleclient instead.

**Comment by brian-brazil** [comment]
The original client is deprecated now.
