### ISSUE TITLE
Failing while building simpleclient_httpserver version parent-0.15.0 using mvn clean install

### ISSUE THREAD

**Issue by shivsrivastava** [prometheus/client_java#953]
[failed_jdk_11.txt](https://github.com/prometheus/client_java/files/15050941/failed_jdk_11.txt)
Package artifact id: simpleclient_httpserver

source code url: https://github.com/prometheus/client_java/tree/parent-0.15.0

Issue Description: Failing while building simpleclient_httpserver version parent-0.15.0 using mvn clean install

JDK Version: 11

Build CMD: mvn clean install

MVN Version: 3.9.6

Error Log: 

Running io.prometheus.client.HistogramTest
Tests run: 15, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec <<< FAILURE!
testTimeWithExemplar(io.prometheus.client.HistogramTest)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.AssertionError: No exemplar found in bucket [0.01, 0.025]
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertNotNull(Assert.java:713)
        at io.prometheus.client.HistogramTest.assertExemplar(HistogramTest.java:301)
        at io.prometheus.client.HistogramTest.testTimeWithExemplar(HistogramTest.java:273)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Running io.prometheus.client.InfoTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec

	

attachement: build log attached (jdk 11)

OS: windows 10

**Comment by fstab** [comment]
Thanks for reporting. Can you update to the latest 1.x version rather than using 0.15.0?

**Comment by shivsrivastava** [comment]
> Thanks for reporting. Can you update to the latest 1.x version rather than using 0.15.0?

Thanks a lot. In our project , req. is to use the 0.15.0 . Would you help me on this please.

**Comment by shivsrivastava** [comment]
> Thanks for reporting. Can you update to the latest 1.x version rather than using 0.15.0?

Hi @fstab ,Can you please update on it.

**Comment by fstab** [comment]
I think this is just a flaky test in the old 0.15.0 version and you can ignore this. Do you experience any issues with histogram exemplars in production?
